function str = background_words()
    % Función para almacenar información del contexto del proyecto
    % Returns: Texto explicativo sobre las Series de Fourier
    
    str = ['La transformada de Fourier es fundamental en el estudio de "Señales y Sistemas". ' ...
           'Para entenderla, es clave comprender el significado físico de las series de Fourier: ' ...
           'cualquier señal continua puede representarse como una superposición infinita de ' ...
           'ondas sinusoidales de diferentes frecuencias. Este programa visualiza este proceso ' ...
           'para una mejor comprensión. La herramienta permite experimentar con diferentes ' ...
           'tipos de señales y observar cómo se descomponen en sus componentes armónicos, ' ...
           'facilitando el aprendizaje de conceptos fundamentales de procesamiento de señales.'];
end 